# Generated by Django 5.2.9 on 2025-12-10 17:01

import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='onet', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='jobs/')),
                ('raw_text', models.TextField(blank=True)),
                ('parsed', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('normalized', models.CharField(blank=True, db_index=True, max_length=256)),
                ('external_id', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(db_index=True)),
                ('rating', models.CharField(max_length=20)),
                ('breakdown', jsonfield.fields.JSONField()),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.jobdescription')),
            ],
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('missing', 'missing'), ('transferable', 'transferable'), ('learnable', 'learnable')], max_length=50)),
                ('importance', models.FloatField(default=0.0)),
                ('suggestion', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='App.matchresult')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512, unique=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('alt_titles', jsonfield.fields.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, default='onet', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='App.domain')),
            ],
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.occupation'),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('metadata', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='App.matchresult')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('raw_text', models.TextField(blank=True)),
                ('parsed', jsonfield.fields.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NLSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('turns', jsonfield.fields.JSONField(default=list)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.resume')),
            ],
        ),
        migrations.AddField(
            model_name='matchresult',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.resume'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('normalized', models.CharField(blank=True, db_index=True, max_length=512)),
                ('element_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('synonyms', jsonfield.fields.JSONField(blank=True, default=list)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='onet', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['normalized'], name='App_skill_normali_485a82_idx'), models.Index(fields=['element_type'], name='App_skill_element_1f5d7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OccupationSkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(blank=True, max_length=64)),
                ('relation_type', models.CharField(choices=[('essential', 'essential'), ('important', 'important'), ('optional', 'optional'), ('other', 'other')], default='other', max_length=32)),
                ('importance', models.FloatField(db_index=True, default=0.0)),
                ('level', models.FloatField(db_index=True, default=0.0)),
                ('provenance', models.CharField(default='onet', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_relations', to='App.occupation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_relations', to='App.skill')),
            ],
        ),
        migrations.CreateModel(
            name='OccupationTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.FloatField(default=0.0)),
                ('provenance', models.CharField(default='onet', max_length=50)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_relations', to='App.occupation')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_relations', to='App.technology')),
            ],
        ),
        migrations.AddIndex(
            model_name='occupation',
            index=models.Index(fields=['name'], name='App_occupat_name_7161a7_idx'),
        ),
        migrations.AddIndex(
            model_name='occupation',
            index=models.Index(fields=['external_id'], name='App_occupat_externa_5a3909_idx'),
        ),
        migrations.AddIndex(
            model_name='occupationskillrelation',
            index=models.Index(fields=['occupation', 'skill'], name='App_occupat_occupat_cf706d_idx'),
        ),
        migrations.AddIndex(
            model_name='occupationskillrelation',
            index=models.Index(fields=['relation_type'], name='App_occupat_relatio_ff48fa_idx'),
        ),
        migrations.AddIndex(
            model_name='occupationskillrelation',
            index=models.Index(fields=['importance'], name='App_occupat_importa_8e11e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='occupationskillrelation',
            unique_together={('occupation', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='occupationtechnology',
            unique_together={('occupation', 'technology')},
        ),
    ]
