# Generated by Django 5.2.9 on 2025-12-05 08:28

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='esco_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='source',
            field=models.CharField(blank=True, default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='synonyms',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='normalized',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
