# Generated by Django 5.2.9 on 2025-12-05 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_skill_embedding_skill_esco_id_skill_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('esco_id', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, default='local', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='esco_id',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='normalized',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.CreateModel(
            name='OccupationSkillRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('essential', 'essential'), ('optional', 'optional'), ('other', 'other')], default='other', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_relations', to='App.occupation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_relations', to='App.skill')),
            ],
            options={
                'indexes': [models.Index(fields=['occupation'], name='App_occupat_occupat_1ad224_idx'), models.Index(fields=['skill'], name='App_occupat_skill_i_07426a_idx'), models.Index(fields=['relation_type'], name='App_occupat_relatio_ff48fa_idx')],
                'unique_together': {('occupation', 'skill', 'relation_type')},
            },
        ),
    ]
